package com.yourpax.app.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF6C63FF)
val PrimaryVariant = Color(0xFF5A52D5)
val PrimaryLight = Color(0xFF9D97FF)
val Secondary = Color(0xFF00D9A6)
val SecondaryVariant = Color(0xFF00B88C)
val Background = Color(0xFFF5F7FA)
val BackgroundDark = Color(0xFF0F0F23)
val Surface = Color(0xFFFFFFFF)
val SurfaceDark = Color(0xFF1A1A2E)
val OnPrimary = Color(0xFFFFFFFF)
val OnBackground = Color(0xFF1A1A2E)
val OnBackgroundDark = Color(0xFFE8E8F0)
val OnSurface = Color(0xFF1A1A2E)
val OnSurfaceDark = Color(0xFFE8E8F0)
val Success = Color(0xFF4CAF50)
val Warning = Color(0xFFFFB74D)
val Error = Color(0xFFFF6B6B)
val Info = Color(0xFF64B5F6)
val CardBackground = Color(0xFFFFFFFF)
val CardBackgroundDark = Color(0xFF222244)
val DividerColor = Color(0xFFE0E0E0)
val DividerColorDark = Color(0xFF2A2A4A)
val SubtleText = Color(0xFF9E9E9E)
val SubtleTextDark = Color(0xFF7A7A9A)
val GradientStart = Color(0xFF6C63FF)
val GradientEnd = Color(0xFF00D9A6)
